-- ===========================================================================
-- BidMart schema for Supabase Postgres
--
-- Run this once in the Supabase dashboard: SQL Editor -> New query -> paste
-- -> Run. It is safe to re-run: everything is created with "if not exists"
-- or "or replace", and policies are dropped before being recreated.
--
-- Identity lives in Supabase Auth (auth.users). Everything the app needs on
-- top of that -- display name and admin flag -- lives in public.profiles,
-- which is filled in automatically by a trigger whenever someone signs up.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text not null,
  role       text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

-- Ids stay integers so existing /product/<id> URLs keep working. "by default"
-- (not "always") lets the migration script insert explicit ids.
create table if not exists public.products (
  id                  bigint generated by default as identity primary key,
  title               text not null,
  description         text not null default '',
  image_url           text not null default '',
  video_url           text not null default '',
  video_path          text not null default '',
  cost_price          numeric(12,2) not null check (cost_price > 0),
  margin_percent      numeric(6,2)  not null check (margin_percent >= 0),
  min_price           numeric(12,2) not null,
  current_highest_bid numeric(12,2),
  highest_bidder_id   uuid references public.profiles(id) on delete set null,
  bid_increment       numeric(12,2) not null check (bid_increment > 0),
  start_time          timestamptz not null default now(),
  end_time            timestamptz not null,
  status              text not null default 'active'
                      check (status in ('active', 'ended_sold', 'ended_unsold')),
  created_at          timestamptz not null default now()
);

create table if not exists public.bids (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references public.products(id) on delete cascade,
  user_id     uuid   not null references public.profiles(id) on delete cascade,
  bidder_name text   not null,
  amount      numeric(12,2) not null check (amount > 0),
  created_at  timestamptz not null default now()
);

create table if not exists public.orders (
  id             bigint generated by default as identity primary key,
  product_id     bigint not null references public.products(id) on delete cascade,
  user_id        uuid   not null references public.profiles(id) on delete cascade,
  final_price    numeric(12,2) not null,
  payment_status text not null default 'awaiting_payment',
  order_status   text not null default 'pending',
  created_at     timestamptz not null default now()
);

create table if not exists public.comments (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references public.products(id) on delete cascade,
  user_id     uuid   not null references public.profiles(id) on delete cascade,
  author_name text   not null,
  body        text   not null check (length(body) between 1 and 1000),
  image_url   text   not null default '',
  image_path  text   not null default '',
  created_at  timestamptz not null default now()
);

create table if not exists public.requests (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  user_name  text not null,
  title      text not null check (length(title) between 1 and 120),
  note       text not null check (length(note) between 1 and 1000),
  image_url  text not null default '',
  image_path text not null default '',
  status     text not null default 'new' check (status in ('new', 'reviewed', 'closed')),
  created_at timestamptz not null default now()
);

create index if not exists bids_product_idx     on public.bids(product_id, created_at desc);
create index if not exists comments_product_idx on public.comments(product_id, created_at desc);
create index if not exists orders_user_idx      on public.orders(user_id);
create index if not exists requests_user_idx    on public.requests(user_id);
create index if not exists products_status_idx  on public.products(status, end_time);

-- ---------------------------------------------------------------------------
-- New signups get a profile automatically
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(new.email, '@', 1)),
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Helpers used by the policies below
--
-- SECURITY DEFINER matters here: without it, a policy on profiles that reads
-- profiles would recurse forever.
-- ---------------------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------------------
-- Row level security
--
-- These are the real access rules. The app's route handlers check permissions
-- too, but these hold even if a request somehow bypasses them.
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.bids     enable row level security;
alter table public.orders   enable row level security;
alter table public.comments enable row level security;
alter table public.requests enable row level security;

-- profiles: you can see and rename yourself; admins can see everyone.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid() and role = 'user');

-- products: the shop window is public; only admins change it.
drop policy if exists products_select on public.products;
create policy products_select on public.products for select using (true);

drop policy if exists products_write on public.products;
create policy products_write on public.products
  for all using (public.is_admin()) with check (public.is_admin());

-- bids: history is public. Inserts go through place_bid(), never directly.
drop policy if exists bids_select on public.bids;
create policy bids_select on public.bids for select using (true);

-- orders: yours, or everything if you're an admin.
drop policy if exists orders_select on public.orders;
create policy orders_select on public.orders
  for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists orders_admin_write on public.orders;
create policy orders_admin_write on public.orders
  for all using (public.is_admin()) with check (public.is_admin());

-- comments: readable by anyone, written as yourself, deleted by you or an admin.
drop policy if exists comments_select on public.comments;
create policy comments_select on public.comments for select using (true);

drop policy if exists comments_insert on public.comments;
create policy comments_insert on public.comments
  for insert with check (user_id = auth.uid());

drop policy if exists comments_delete on public.comments;
create policy comments_delete on public.comments
  for delete using (user_id = auth.uid() or public.is_admin());

-- requests: private between the customer and the shop.
drop policy if exists requests_select on public.requests;
create policy requests_select on public.requests
  for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists requests_insert on public.requests;
create policy requests_insert on public.requests
  for insert with check (user_id = auth.uid());

drop policy if exists requests_update on public.requests;
create policy requests_update on public.requests
  for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists requests_delete on public.requests;
create policy requests_delete on public.requests
  for delete using (user_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
-- place_bid()
--
-- The JSON version read the product, checked the amount, then wrote -- so two
-- bids arriving together could both "win". Locking the product row here makes
-- that impossible: the second bid waits, then re-checks against the first.
-- ---------------------------------------------------------------------------

create or replace function public.place_bid(p_product_id bigint, p_amount numeric)
returns public.bids
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products;
  v_profile public.profiles;
  v_floor   numeric;
  v_bid     public.bids;
begin
  select * into v_profile from public.profiles where id = auth.uid();
  if v_profile is null then
    raise exception 'You must be logged in to bid.' using errcode = '42501';
  end if;

  -- FOR UPDATE holds the row until this transaction commits.
  select * into v_product from public.products where id = p_product_id for update;
  if v_product is null then
    raise exception 'Product not found.' using errcode = 'P0002';
  end if;
  if v_product.status <> 'active' or v_product.end_time <= now() then
    raise exception 'This auction has ended.' using errcode = 'P0001';
  end if;

  v_floor := coalesce(v_product.current_highest_bid + v_product.bid_increment, v_product.min_price);
  if p_amount < v_floor then
    raise exception 'Your bid must be at least %.', v_floor using errcode = 'P0001';
  end if;

  insert into public.bids (product_id, user_id, bidder_name, amount)
  values (p_product_id, v_profile.id, v_profile.name, p_amount)
  returning * into v_bid;

  update public.products
     set current_highest_bid = p_amount,
         highest_bidder_id   = v_profile.id
   where id = p_product_id;

  return v_bid;
end;
$$;

-- ---------------------------------------------------------------------------
-- close_expired_auctions()
--
-- Same job as the old JS helper: end auctions past their time, and raise an
-- order for the winner. Doing it in one statement per step means it can't
-- half-finish, and the "not exists" guard keeps it idempotent.
-- ---------------------------------------------------------------------------

create or replace function public.close_expired_auctions()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.orders (product_id, user_id, final_price)
  select p.id, p.highest_bidder_id, p.current_highest_bid
    from public.products p
   where p.status = 'active'
     and p.end_time <= now()
     and p.highest_bidder_id is not null
     and not exists (select 1 from public.orders o where o.product_id = p.id);

  update public.products
     set status = case when highest_bidder_id is not null then 'ended_sold' else 'ended_unsold' end
   where status = 'active' and end_time <= now();
end;
$$;

-- ---------------------------------------------------------------------------
-- resync_identity_sequences()
--
-- The migration inserts rows with their original ids. Identity sequences don't
-- notice that, so the next generated id would collide. This pushes each
-- sequence past the highest id present. Harmless to run at any time.
-- ---------------------------------------------------------------------------

create or replace function public.resync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
begin
  foreach t in array array['products', 'bids', 'orders', 'comments', 'requests'] loop
    execute format(
      'select setval(pg_get_serial_sequence(''public.%I'', ''id''),
                     coalesce((select max(id) from public.%I), 0) + 1, false)', t, t);
  end loop;
end;
$$;

grant execute on function public.place_bid(bigint, numeric) to authenticated;
grant execute on function public.close_expired_auctions() to anon, authenticated;
grant execute on function public.resync_identity_sequences() to service_role;
